# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{win32screenshot}
  s.version = "1.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Jarmo Pertman}, %q{Aslak Hellesøy}]
  s.date = %q{2011-08-18}
  s.description = %q{Capture Screenshots on Windows with Ruby to bmp, gif, jpg or png formats!}
  s.email = [%q{jarmo.p@gmail.com}, %q{aslak.hellesoy@gmail.com}]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".yardopts",
    "History.rdoc",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ext/CORE_RL_bzlib_.dll",
    "ext/CORE_RL_jpeg_.dll",
    "ext/CORE_RL_lcms_.dll",
    "ext/CORE_RL_magick_.dll",
    "ext/CORE_RL_png_.dll",
    "ext/CORE_RL_ttf_.dll",
    "ext/CORE_RL_wand_.dll",
    "ext/CORE_RL_zlib_.dll",
    "ext/ImageMagick-License.txt",
    "ext/X11.dll",
    "ext/identify.exe",
    "ext/modules/coders/IM_MOD_RL_bmp_.dll",
    "ext/modules/coders/IM_MOD_RL_gif_.dll",
    "ext/modules/coders/IM_MOD_RL_jpeg_.dll",
    "ext/modules/coders/IM_MOD_RL_png_.dll",
    "ext/mogrify.exe",
    "ext/msvcr100.dll",
    "ext/vcomp100.dll",
    "lib/win32/screenshot.rb",
    "lib/win32/screenshot/bitmap_maker.rb",
    "lib/win32/screenshot/image.rb",
    "lib/win32/screenshot/take.rb",
    "spec/spec_helper.rb",
    "spec/win32/screenshot/image_spec.rb",
    "spec/win32/screenshot/take_spec.rb",
    "win32screenshot.gemspec"
  ]
  s.homepage = %q{http://github.com/jarmo/win32screenshot}
  s.rdoc_options = [%q{--main}, %q{README.rdoc}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.4}
  s.summary = %q{Capture Screenshots on Windows with Ruby to bmp, gif, jpg or png formats!}
  s.test_files = [
    "spec/spec_helper.rb",
    "spec/win32/screenshot/image_spec.rb",
    "spec/win32/screenshot/take_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi>, ["~> 1.0"])
      s.add_runtime_dependency(%q<mini_magick>, ["~> 3.2.0"])
      s.add_runtime_dependency(%q<rautomation>, ["~> 0.6.3"])
      s.add_development_dependency(%q<rspec>, ["~> 2.5"])
    else
      s.add_dependency(%q<ffi>, ["~> 1.0"])
      s.add_dependency(%q<mini_magick>, ["~> 3.2.0"])
      s.add_dependency(%q<rautomation>, ["~> 0.6.3"])
      s.add_dependency(%q<rspec>, ["~> 2.5"])
    end
  else
    s.add_dependency(%q<ffi>, ["~> 1.0"])
    s.add_dependency(%q<mini_magick>, ["~> 3.2.0"])
    s.add_dependency(%q<rautomation>, ["~> 0.6.3"])
    s.add_dependency(%q<rspec>, ["~> 2.5"])
  end
end

